repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: debug-statements
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-json
    - id: check-symlinks
    - id: check-vcs-permalinks
    - id: check-xml
    - id: check-yaml
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key
    - id: forbid-new-submodules
    - id: flake8
      args: ['--ignore=E501,W503']

- repo: https://github.com/python/black
  rev: 19.3b0
  hooks:
    - id: black
      args: ['--diff']

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.20
  hooks:
  - id: isort
    args: ['--check-only']
