dist: xenial
sudo: yes
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install pip -U
  - pip install -r requirements-dev.txt
before_script:
  - make lint
script:
  pytest
after_success:
  codecov
